# ML Project 2 - Causal Inference

## 1. Import Libraries and Load Data

In [1]:
import numpy as np
import pandas as pd

import statsmodels.api as sm
from linearmodels.iv import IV2SLS

import warnings

warnings.filterwarnings("ignore")

RANDOM_STATE = 42

In [2]:
df_desc = pd.read_stata("../data/oregonhie_descriptive_vars.dta")
df_state = pd.read_stata("../data/oregonhie_stateprograms_vars.dta")
df_ed = pd.read_stata("../data/oregonhie_ed_vars.dta")

# merge by person_id
df = df_desc.merge(df_state, on="person_id", how="left").merge(
    df_ed, on="person_id", how="left"
)

df.head()

,person_id,household_id,treatment,draw_treat,draw_lottery,applied_app,approved_app,dt_notify_lottery,dt_retro_coverage,dt_app_decision,...,ed_charg_tot_pre_ed,ed_charg_tot_ed,any_hiun_pre_ed,any_hiun_ed,num_hiun_pre_cens_ed,num_hiun_cens_ed,any_loun_pre_ed,any_loun_ed,num_loun_pre_cens_ed,num_loun_cens_ed
0,1.0,100001.0,Selected,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Submitted an Application to OHP,No,2008-08-12,2008-09-08,2008-12-31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,100002.0,Selected,Draw 6: selected in lottery 07/01/2008,Lottery Draw 6,Did NOT submit an application to OHP,No,2008-07-14,2008-08-08,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,100003.0,Not selected,NaN,Lottery Draw 2,NaN,NaN,2008-04-07,2008-04-08,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,100004.0,Not selected,NaN,Lottery Draw 8,NaN,NaN,2008-09-11,2008-10-08,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,100005.0,Selected,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Did NOT submit an application to OHP,No,2008-08-12,2008-09-08,NaT,...,0.0,0.0,No,No,0.0,0.0,No,No,0.0,0.0

## 2. Part(a) - Initial Data Pre-processing and Balance Check

In [3]:
# create number of people in household on lottery list (numhh_list) dummies
numhh_dummies = pd.get_dummies(
    df["numhh_list"], prefix="numhh", drop_first=True, dtype="int"
)
df = pd.concat([df, numhh_dummies], axis=1)

In [4]:
# map treatment into binary variables
df["treatment"].replace({"Selected": 1, "Not selected": 0}, inplace=True)

# handle missing value in sample_ed
df["sample_ed"] = df["sample_ed"].fillna(0)

# map female_list into binary variables
df["female_list"].replace({"1: Female": 1, "0: Male": 0}, inplace=True)

# map self_list into binary variables
df["female_list"].replace({"1: Female": 1, "0: Male": 0}, inplace=True)

df["self_list"].replace({"Signed self up": 1, "Did NOT sign self up": 0}, inplace=True)

df["any_visit_pre_ed"].replace({"Yes": 1, "No": 0}, inplace=True)

df.head()

,person_id,household_id,treatment,draw_treat,draw_lottery,applied_app,approved_app,dt_notify_lottery,dt_retro_coverage,dt_app_decision,...,any_hiun_pre_ed,any_hiun_ed,num_hiun_pre_cens_ed,num_hiun_cens_ed,any_loun_pre_ed,any_loun_ed,num_loun_pre_cens_ed,num_loun_cens_ed,numhh_signed self up + 1 additional person,numhh_signed self up + 2 additional people
0,1.0,100001.0,1,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Submitted an Application to OHP,No,2008-08-12,2008-09-08,2008-12-31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
1,2.0,100002.0,1,Draw 6: selected in lottery 07/01/2008,Lottery Draw 6,Did NOT submit an application to OHP,No,2008-07-14,2008-08-08,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
2,3.0,100003.0,0,NaN,Lottery Draw 2,NaN,NaN,2008-04-07,2008-04-08,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
3,4.0,100004.0,0,NaN,Lottery Draw 8,NaN,NaN,2008-09-11,2008-10-08,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
4,5.0,100005.0,1,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Did NOT submit an application to OHP,No,2008-08-12,2008-09-08,NaT,...,No,No,0.0,0.0,No,No,0.0,0.0,0,0

### Full sample balance check

In [5]:
y = df["sample_ed"]

X = pd.concat([df[["treatment"]], numhh_dummies], axis=1)
X = sm.add_constant(X)

full_model = sm.OLS(endog=y, exog=X, missing="drop")
result = full_model.fit()
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              sample_ed   R-squared:                       0.002
Model:                            OLS   Adj. R-squared:                  0.002
Method:                 Least Squares   F-statistic:                     59.03
Date:                Mon, 02 Mar 2026   Prob (F-statistic):           4.17e-38
Time:                        20:11:15   Log-Likelihood:                -49627.
No. Observations:               74922   AIC:                         9.926e+04
Df Residuals:                   74918   BIC:                         9.930e+04
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================================================
                                                 coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------
const                                          0.3419      0.002    147.875      0.000       0.337       0.346
treatment                                     -0.0014      0.004     -0.396      0.692      -0.008       0.006
numhh_signed self up + 1 additional person    -0.0539      0.004    -12.966      0.000      -0.062      -0.046
numhh_signed self up + 2 additional people    -0.0116      0.037     -0.309      0.757      -0.085       0.062
==============================================================================
Omnibus:                   509007.907   Durbin-Watson:                   1.993
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            13254.683
Skew:                           0.725   Prob(JB):                         0.00
Kurtosis:                       1.536   Cond. No.                         24.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### Sample balance checks

In [6]:
# restrict to ED samples
df_ed_sample = df[df["sample_ed"] != 0.0].copy()

df_ed_sample.shape

(24646, 146)

In [7]:
X_sample = pd.concat(
    [df_ed_sample[["treatment"]], df_ed_sample[numhh_dummies.columns]], axis=1
)
X_sample = sm.add_constant(X_sample)

X_sample

,const,treatment,numhh_signed self up + 1 additional person,numhh_signed self up + 2 additional people
4,1.0,1,0,0
7,1.0,0,1,0
8,1.0,0,0,0
15,1.0,0,1,0
17,1.0,0,0,0
...,...,...,...,...
74906,1.0,1,0,0
74910,1.0,1,1,0
74914,1.0,1,0,0
74917,1.0,0,0,0
74919,1.0,0,0,0

#### (i) Year of birth

In [8]:
balance_yob = sm.OLS(endog=df_ed_sample["birthyear_list"], exog=X_sample, missing="drop")
result_balance_yob = balance_yob.fit()
print(result_balance_yob.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         birthyear_list   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                     1.825
Date:                Mon, 02 Mar 2026   Prob (F-statistic):              0.140
Time:                        20:11:15   Log-Likelihood:                -96304.
No. Observations:               24646   AIC:                         1.926e+05
Df Residuals:                   24642   BIC:                         1.926e+05
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================================================
                                                 coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------
const                                       1968.2778      0.102   1.93e+04      0.000    1968.078    1968.478
treatment                                      0.0976      0.160      0.609      0.543      -0.216       0.412
numhh_signed self up + 1 additional person     0.4048      0.195      2.076      0.038       0.023       0.787
numhh_signed self up + 2 additional people     0.6551      1.675      0.391      0.696      -2.628       3.938
==============================================================================
Omnibus:                    12450.079   Durbin-Watson:                   1.978
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1365.608
Skew:                          -0.116   Prob(JB):                    2.90e-297
Kurtosis:                       1.870   Cond. No.                         24.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

#### (ii) Female

In [9]:
balance_female = sm.OLS(endog=df_ed_sample["female_list"], exog=X_sample, missing="drop")
result_balance_female = balance_female.fit()
print(result_balance_female.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            female_list   R-squared:                       0.002
Model:                            OLS   Adj. R-squared:                  0.002
Method:                 Least Squares   F-statistic:                     15.03
Date:                Mon, 02 Mar 2026   Prob (F-statistic):           9.01e-10
Time:                        20:11:15   Log-Likelihood:                -17757.
No. Observations:               24646   AIC:                         3.552e+04
Df Residuals:                   24642   BIC:                         3.556e+04
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================================================
                                                 coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------
const                                          0.5605      0.004    132.958      0.000       0.552       0.569
treatment                                     -0.0100      0.007     -1.510      0.131      -0.023       0.003
numhh_signed self up + 1 additional person    -0.0495      0.008     -6.146      0.000      -0.065      -0.034
numhh_signed self up + 2 additional people     0.0060      0.069      0.087      0.931      -0.130       0.142
==============================================================================
Omnibus:                    86511.414   Durbin-Watson:                   2.012
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4079.108
Skew:                          -0.187   Prob(JB):                         0.00
Kurtosis:                       1.042   Cond. No.                         24.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

#### (iii) Signed up self for lottery

In [10]:
balance_self = sm.OLS(endog=df_ed_sample["self_list"], exog=X_sample, missing="drop")
result_balance_self = balance_self.fit()
print(result_balance_self.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              self_list   R-squared:                       0.446
Model:                            OLS   Adj. R-squared:                  0.446
Method:                 Least Squares   F-statistic:                     6611.
Date:                Mon, 02 Mar 2026   Prob (F-statistic):               0.00
Time:                        20:11:15   Log-Likelihood:                 1774.3
No. Observations:               24646   AIC:                            -3541.
Df Residuals:                   24642   BIC:                            -3508.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================================================
                                                 coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------
const                                          0.9998      0.002    523.840      0.000       0.996       1.004
treatment                                      0.0006      0.003      0.203      0.839      -0.005       0.006
numhh_signed self up + 1 additional person    -0.5004      0.004   -137.304      0.000      -0.508      -0.493
numhh_signed self up + 2 additional people    -0.6542      0.031    -20.893      0.000      -0.716      -0.593
==============================================================================
Omnibus:                     1107.005   Durbin-Watson:                   2.004
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3883.005
Skew:                           0.016   Prob(JB):                         0.00
Kurtosis:                       4.944   Cond. No.                         24.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

#### (iv) Any ED visit, pre-randomization (censored)

In [11]:
balance_visit_pre_ed = sm.OLS(endog=df_ed_sample["any_visit_pre_ed"], exog=X_sample, missing="drop")
result_balance_visit_pre_ed = balance_visit_pre_ed.fit()
print(result_balance_visit_pre_ed.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:       any_visit_pre_ed   R-squared:                       0.015
Model:                            OLS   Adj. R-squared:                  0.015
Method:                 Least Squares   F-statistic:                     124.2
Date:                Mon, 02 Mar 2026   Prob (F-statistic):           7.55e-80
Time:                        20:11:16   Log-Likelihood:                -15848.
No. Observations:               24646   AIC:                         3.170e+04
Df Residuals:                   24642   BIC:                         3.174e+04
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================================================
                                                 coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------
const                                          0.3400      0.004     87.146      0.000       0.332       0.348
treatment                                      0.0045      0.006      0.734      0.463      -0.008       0.016
numhh_signed self up + 1 additional person    -0.1404      0.007    -18.842      0.000      -0.155      -0.126
numhh_signed self up + 2 additional people    -0.2286      0.064     -3.571      0.000      -0.354      -0.103
==============================================================================
Omnibus:                   286136.499   Durbin-Watson:                   1.994
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4315.157
Skew:                           0.782   Prob(JB):                         0.00
Kurtosis:                       1.675   Cond. No.                         24.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

#### (v) Number of ED visits, pre-randomization (censored)

In [12]:
balance_num_visit = sm.OLS(endog=df_ed_sample["num_visit_pre_cens_ed"], exog=X_sample, missing="drop")
result_balance_num_visit = balance_num_visit.fit()
print(result_balance_num_visit.summary())

                              OLS Regression Results
=================================================================================
Dep. Variable:     num_visit_pre_cens_ed   R-squared:                       0.010
Model:                               OLS   Adj. R-squared:                  0.009
Method:                    Least Squares   F-statistic:                     78.89
Date:                   Mon, 02 Mar 2026   Prob (F-statistic):           8.76e-51
Time:                           20:11:16   Log-Likelihood:                -50165.
No. Observations:                  24634   AIC:                         1.003e+05
Df Residuals:                      24630   BIC:                         1.004e+05
Df Model:                              3
Covariance Type:               nonrobust
==============================================================================================================
                                                 coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------
const                                          0.8651      0.016     55.025      0.000       0.834       0.896
treatment                                      0.0022      0.025      0.090      0.928      -0.046       0.051
numhh_signed self up + 1 additional person    -0.4508      0.030    -15.016      0.000      -0.510      -0.392
numhh_signed self up + 2 additional people    -0.5786      0.258     -2.244      0.025      -1.084      -0.073
==============================================================================
Omnibus:                    22995.429   Durbin-Watson:                   2.018
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           902515.954
Skew:                           4.596   Prob(JB):                         0.00
Kurtosis:                      31.192   Cond. No.                         24.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## 3. Part(b) - Causal Effect of Being Selected by Lottery

In [13]:
# restrict to Portland ED sample
df_b = df_ed_sample.copy()

In [14]:
# rename for easier reference
df_b.rename(columns={"ohp_all_ever_matchn_30sep2009": "medicaid_enroll"}, inplace=True)

# map to binary variables
df_b["medicaid_enroll"].replace({"Enrolled": 1, "NOT enrolled": 0}, inplace=True)

df_b.head()

,person_id,household_id,treatment,draw_treat,draw_lottery,applied_app,approved_app,dt_notify_lottery,dt_retro_coverage,dt_app_decision,...,any_hiun_pre_ed,any_hiun_ed,num_hiun_pre_cens_ed,num_hiun_cens_ed,any_loun_pre_ed,any_loun_ed,num_loun_pre_cens_ed,num_loun_cens_ed,numhh_signed self up + 1 additional person,numhh_signed self up + 2 additional people
4,5.0,100005.0,1,Draw 7: selected in lottery 08/01/2008,Lottery Draw 7,Did NOT submit an application to OHP,No,2008-08-12,2008-09-08,NaT,...,No,No,0.0,0.0,No,No,0.0,0.0,0,0
7,8.0,102094.0,0,NaN,Lottery Draw 8,NaN,NaN,2008-09-11,2008-10-08,NaT,...,No,Yes,0.0,2.0,No,No,0.0,0.0,1,0
8,9.0,100009.0,0,NaN,Lottery Draw 1,NaN,NaN,2008-03-10,2008-03-11,NaT,...,Yes,No,1.0,0.0,No,No,0.0,0.0,0,0
15,16.0,140688.0,0,NaN,Lottery Draw 2,NaN,NaN,2008-04-07,2008-04-08,NaT,...,Yes,Yes,1.0,5.0,No,No,0.0,0.0,1,0
17,18.0,100018.0,0,NaN,Lottery Draw 4,NaN,NaN,2008-05-09,2008-06-09,NaT,...,No,No,0.0,0.0,Yes,No,2.0,0.0,0,0

In [15]:
features = ["treatment", "birthyear_list", "female_list", "self_list", "any_visit_pre_ed", "num_visit_pre_cens_ed"]

features = pd.concat(
    [df_ed_sample[features], df_ed_sample[numhh_dummies.columns]], axis=1
)
features = sm.add_constant(features)

medicaid_enroll_causal = sm.OLS(endog=df_b["medicaid_enroll"], exog=features, missing="drop")
result_medicaid_enroll_causal = medicaid_enroll_causal.fit()
print(result_medicaid_enroll_causal.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        medicaid_enroll   R-squared:                       0.098
Model:                            OLS   Adj. R-squared:                  0.098
Method:                 Least Squares   F-statistic:                     334.2
Date:                Mon, 02 Mar 2026   Prob (F-statistic):               0.00
Time:                        20:11:16   Log-Likelihood:                -12745.
No. Observations:               24634   AIC:                         2.551e+04
Df Residuals:                   24625   BIC:                         2.558e+04
Df Model:                           8
Covariance Type:            nonrobust
==============================================================================================================
                                                 coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------
const                                         -1.1022      0.423     -2.604      0.009      -1.932      -0.273
treatment                                      0.2479      0.005     45.884      0.000       0.237       0.259
birthyear_list                                 0.0006      0.000      2.660      0.008       0.000       0.001
female_list                                    0.0840      0.005     16.069      0.000       0.074       0.094
self_list                                      0.0547      0.012      4.741      0.000       0.032       0.077
any_visit_pre_ed                               0.0480      0.007      6.758      0.000       0.034       0.062
num_visit_pre_cens_ed                          0.0125      0.002      7.112      0.000       0.009       0.016
numhh_signed self up + 1 additional person     0.0072      0.009      0.818      0.413      -0.010       0.024
numhh_signed self up + 2 additional people    -0.1636      0.057     -2.871      0.004      -0.275      -0.052
==============================================================================
Omnibus:                     3287.623   Durbin-Watson:                   2.010
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4503.683
Skew:                           1.029   Prob(JB):                         0.00
Kurtosis:                       2.610   Cond. No.                     3.22e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.22e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

## 4. Part(c) - Causal Effect of Enrolling into a Medicaid Program on ED Visits

In [16]:
df_c = df_b.copy()

y_any = df_c["any_visit_ed"]
y_num = df_c["num_visit_cens_ed"]

### First Stage

In [17]:
first_stage = sm.OLS(endog=df_c["medicaid_enroll"],exog=X_sample, missing="drop")

result_first_stage = first_stage.fit()
print(result_first_stage.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        medicaid_enroll   R-squared:                       0.077
Model:                            OLS   Adj. R-squared:                  0.077
Method:                 Least Squares   F-statistic:                     687.5
Date:                Mon, 02 Mar 2026   Prob (F-statistic):               0.00
Time:                        20:11:16   Log-Likelihood:                -13032.
No. Observations:               24646   AIC:                         2.607e+04
Df Residuals:                   24642   BIC:                         2.611e+04
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================================================
                                                 coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------
const                                          0.1517      0.003     43.588      0.000       0.145       0.159
treatment                                      0.2474      0.005     45.287      0.000       0.237       0.258
numhh_signed self up + 1 additional person    -0.0363      0.007     -5.469      0.000      -0.049      -0.023
numhh_signed self up + 2 additional people    -0.2167      0.057     -3.795      0.000      -0.329      -0.105
==============================================================================
Omnibus:                     3492.848   Durbin-Watson:                   2.006
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4909.232
Skew:                           1.076   Prob(JB):                         0.00
Kurtosis:                       2.612   Cond. No.                         24.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### Second Stage

#### (i) Outcome: Any ED visit (binary)

In [18]:
features_iv = ["birthyear_list", "female_list", "self_list", "any_visit_pre_ed", "num_visit_pre_cens_ed"]

features_iv = pd.concat(
    [df_ed_sample[features_iv], df_ed_sample[numhh_dummies.columns]], axis=1
)
features_iv = sm.add_constant(features_iv)

iv_any = IV2SLS(dependent=df_c["any_visit_ed"], endog=df_c["medicaid_enroll"], exog=features_iv, instruments=df_c["treatment"])
res_iv_any_2sls = iv_any.fit()
print(res_iv_any_2sls)

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:       any_visit_ed.Yes   R-squared:                      0.1722
Estimator:                    IV-2SLS   Adj. R-squared:                 0.1719
No. Observations:               24634   F-statistic:                    5751.9
Date:                Mon, Mar 02 2026   P-value (F-stat)                0.0000
Time:                        20:11:16   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                             Parameter Estimates
==============================================================================================================
                                            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------
const                                          1.5722     0.4547     3.4578     0.0005      0.6810      2.4634
birthyear_list                                -0.0007     0.0002    -2.9629     0.0030     -0.0011     -0.0002
female_list.1                                  0.0010     0.0059     0.1620     0.8713     -0.0106      0.0125
self_list.1                                    0.0037     0.0113     0.3276     0.7432     -0.0184      0.0257
any_visit_pre_ed.1                             0.2449     0.0081     30.064     0.0000      0.2290      0.2609
num_visit_pre_cens_ed                          0.0467     0.0016     28.627     0.0000      0.0435      0.0499
numhh_signed self up + 1 additional person    -0.0811     0.0087    -9.3261     0.0000     -0.0981     -0.0640
numhh_signed self up + 2 additional people    -0.0877     0.0527    -1.6624     0.0964     -0.1911      0.0157
medicaid_enroll.1                              0.0716     0.0231     3.0951     0.0020      0.0263      0.1170
==============================================================================================================

Endogenous: medicaid_enroll.1
Instruments: treatment.1
Robust Covariance (Heteroskedastic)
Debiased: False

#### (ii) Outcome: Number of ED visits (censored)

In [19]:
iv_num = IV2SLS(dependent=df_c["num_visit_cens_ed"], endog=df_c["medicaid_enroll"], exog=features_iv, instruments=df_c["treatment"])
res_iv_num_2sls = iv_num.fit()
print(res_iv_num_2sls)

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:      num_visit_cens_ed   R-squared:                      0.3398
Estimator:                    IV-2SLS   Adj. R-squared:                 0.3396
No. Observations:               24615   F-statistic:                    2684.8
Date:                Mon, Mar 02 2026   P-value (F-stat)                0.0000
Time:                        20:11:16   Distribution:                  chi2(8)
Cov. Estimator:                robust

                                             Parameter Estimates
==============================================================================================================
                                            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------
const                                          1.5541     1.9070     0.8150     0.4151     -2.1834      5.2917
birthyear_list                                -0.0006     0.0010    -0.5923     0.5536     -0.0025      0.0013
female_list.1                                 -0.0314     0.0268    -1.1710     0.2416     -0.0840      0.0212
self_list.1                                   -0.0028     0.0357    -0.0790     0.9371     -0.0728      0.0672
any_visit_pre_ed.1                            -0.0967     0.0593    -1.6290     0.1033     -0.2130      0.0196
num_visit_pre_cens_ed                          0.7573     0.0281     26.961     0.0000      0.7022      0.8123
numhh_signed self up + 1 additional person    -0.2692     0.0302    -8.9285     0.0000     -0.3283     -0.2101
numhh_signed self up + 2 additional people    -0.3662     0.1385    -2.6451     0.0082     -0.6376     -0.0949
medicaid_enroll.1                              0.3880     0.1056     3.6730     0.0002      0.1809      0.5950
==============================================================================================================

Endogenous: medicaid_enroll.1
Instruments: treatment.1
Robust Covariance (Heteroskedastic)
Debiased: False